name : continuous-integration
env:
  USERNAME: '${{ secrets.USERNAME }}'
  PASSWORD: '${{ secrets.PASSWORD }}'
on : [push]
jobs:
  Pruebas-de-SAST:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ejecución de pruebas de SAST"
  Crea-file-credenciales:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Crea credenciales file"
      - run: echo "[credentials] \nusername : ${{USERNAME}} \npassword : ${{PASSWORD}}" > credentials.ini
     
  Build-docker-image:
    runs-on: ubuntu-latest
    steps:    
      - run: echo "Construye docker"
      - run: docker build -t devops_ws . --tag devops_ws_:$(date +%s)
