name : continuous-integration
on : [push]
jobs:
  Pruebas-de-SAST:
    steps:
      - run: echo "Ejecución de pruebas de SAST"
  Crea-file-credenciales:
    steps:
      - run: echo "Crea credenciales file"
  Build docker image:
    steps:    
      - run: echo "Construye docker"
      - run: docker build -t devops_ws . --tag devops_ws_:$(date +%s)
